[tool.poetry]
name = "final_project"
version = "0.1.0"
description = "Solution for Forest Cover Type Prediction competition"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/MeSugar/final_project"
repository = "https://github.com/MeSugar/final_project"
keywords = ["final project"]
authors = ["MeSugar <vlasov3454@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
